### ISSUE TITLE
Check that SDK demo VM works without internet connection

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-y1-demo#26]
Final step. Be safe in Brussels ...

**Comment by StefanUPB** [comment]
Implemented offline descriptorgen: https://github.com/sonata-nfv/tng-sdk-descriptorgen/pull/47
(Jenkins currently fails in the publication stage as registry.sonata-nfv.eu seems to time out)

**Comment by mpeuster** [comment]
Does not make sense ... we need to push to 5GTANGO SP etc anyways ... didn't thought about this. However, the tools should not rely on a very fast internet connection.
