### ISSUE TITLE
Create step-by-step demo walkthrough in wiki

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-y1-demo#27]
https://github.com/sonata-nfv/tng-y1-demo/wiki/Y1-WP4-SDK-Demo-Walkthrough/

**Comment by StefanUPB** [comment]
Added first draft here: https://github.com/sonata-nfv/tng-y1-demo/wiki/SDK-Demo-Walkthrough

**Comment by mpeuster** [comment]
I am on it right now. 

TODO's left:

- [ ] document usage of validator GUI
- [ ] document packaging
- [ ] document uploading to 5GTANGO
- [ ] add OSM flavor to it (ending with uploading to OSM)
- [ ] document GUI installation
